FROM golang:1.24.6-alpine AS builder

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main ./cmd/ingestor

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .

COPY --from=builder /app ./

RUN mkdir -p /app/config /app/database

CMD ["/app/main"]
