// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/trades": {
            "get": {
                "description": "Retorna dados agregados de um ticker específico, podendo filtrar por data de início",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "trade"
                ],
                "summary": "Obtém dados agregados de negociações",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código do ticker (ex: PETR4)",
                        "name": "ticker",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data de início no formato YYYY-MM-DD",
                        "name": "data_inicio",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/trade.AggregatedData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "trade.AggregatedData": {
            "type": "object",
            "properties": {
                "max_daily_volume": {
                    "type": "integer"
                },
                "max_range_value": {
                    "type": "number"
                },
                "ticker": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "B3 Reader API",
	Description:      "API para leitura e agregação de dados de trades da B3.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
